// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD53LIgCc8DAIf0RORiSI1Z-yu0ekL3QHk',
    appId: '1:499735213666:web:cb73e47104ec08d469033b',
    messagingSenderId: '499735213666',
    projectId: 'expense-app-30efb',
    authDomain: 'expense-app-30efb.firebaseapp.com',
    storageBucket: 'expense-app-30efb.firebasestorage.app',
    measurementId: 'G-7RSZJFR52L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9vYnzpyTX85OvaA2FVmB7UaBFX0Zi21U',
    appId: '1:499735213666:android:88bddbc9bbbdad9669033b',
    messagingSenderId: '499735213666',
    projectId: 'expense-app-30efb',
    storageBucket: 'expense-app-30efb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaTE0Vi7uwupAVsMnyBnntL53wbKwR_cU',
    appId: '1:499735213666:ios:8f2fe341d7dc79d469033b',
    messagingSenderId: '499735213666',
    projectId: 'expense-app-30efb',
    storageBucket: 'expense-app-30efb.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaTE0Vi7uwupAVsMnyBnntL53wbKwR_cU',
    appId: '1:499735213666:ios:8f2fe341d7dc79d469033b',
    messagingSenderId: '499735213666',
    projectId: 'expense-app-30efb',
    storageBucket: 'expense-app-30efb.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD53LIgCc8DAIf0RORiSI1Z-yu0ekL3QHk',
    appId: '1:499735213666:web:10d84fa5e855956c69033b',
    messagingSenderId: '499735213666',
    projectId: 'expense-app-30efb',
    authDomain: 'expense-app-30efb.firebaseapp.com',
    storageBucket: 'expense-app-30efb.firebasestorage.app',
    measurementId: 'G-5CY1LDFZP8',
  );
}
