// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1VN-MkCV6asZdDXDHmmXSxQ97m-NTh3E',
    appId: '1:799889518764:web:1856b4abb42fd72d7a6f09',
    messagingSenderId: '799889518764',
    projectId: 'school-management-app-963c1',
    authDomain: 'school-management-app-963c1.firebaseapp.com',
    storageBucket: 'school-management-app-963c1.firebasestorage.app',
    measurementId: 'G-PZKF1YYN5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkwrF93vRGvFmbwLlvbMnf7HzNBJzHNNU',
    appId: '1:799889518764:android:701467f6813a4f757a6f09',
    messagingSenderId: '799889518764',
    projectId: 'school-management-app-963c1',
    storageBucket: 'school-management-app-963c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDDmi_RSMBCHH04PWSZBKTww5AK_y39rk',
    appId: '1:799889518764:ios:677176ccdabb190e7a6f09',
    messagingSenderId: '799889518764',
    projectId: 'school-management-app-963c1',
    storageBucket: 'school-management-app-963c1.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDDmi_RSMBCHH04PWSZBKTww5AK_y39rk',
    appId: '1:799889518764:ios:677176ccdabb190e7a6f09',
    messagingSenderId: '799889518764',
    projectId: 'school-management-app-963c1',
    storageBucket: 'school-management-app-963c1.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1VN-MkCV6asZdDXDHmmXSxQ97m-NTh3E',
    appId: '1:799889518764:web:bc63e27a807ec5047a6f09',
    messagingSenderId: '799889518764',
    projectId: 'school-management-app-963c1',
    authDomain: 'school-management-app-963c1.firebaseapp.com',
    storageBucket: 'school-management-app-963c1.firebasestorage.app',
    measurementId: 'G-TQM2ECFXP3',
  );
}
