// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLlDP3WCl5BNIVwVJ1WMpxe4J0jYSoKeE',
    appId: '1:925336818094:web:d40c7e1540eee91181783f',
    messagingSenderId: '925336818094',
    projectId: 'book-5a365',
    authDomain: 'book-5a365.firebaseapp.com',
    storageBucket: 'book-5a365.firebasestorage.app',
    measurementId: 'G-HLL0WG4Z2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3nTED3iZKj9MrfwU9pPtb8HvOkIwqg4',
    appId: '1:925336818094:android:d29f3e287cfe1f4b81783f',
    messagingSenderId: '925336818094',
    projectId: 'book-5a365',
    storageBucket: 'book-5a365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRVD9GaAmC63qWeAIlWMTW_-XvrHjr_U',
    appId: '1:925336818094:ios:8296d5331f40c7d781783f',
    messagingSenderId: '925336818094',
    projectId: 'book-5a365',
    storageBucket: 'book-5a365.firebasestorage.app',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzRVD9GaAmC63qWeAIlWMTW_-XvrHjr_U',
    appId: '1:925336818094:ios:8296d5331f40c7d781783f',
    messagingSenderId: '925336818094',
    projectId: 'book-5a365',
    storageBucket: 'book-5a365.firebasestorage.app',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLlDP3WCl5BNIVwVJ1WMpxe4J0jYSoKeE',
    appId: '1:925336818094:web:eb15f004b649f6c981783f',
    messagingSenderId: '925336818094',
    projectId: 'book-5a365',
    authDomain: 'book-5a365.firebaseapp.com',
    storageBucket: 'book-5a365.firebasestorage.app',
    measurementId: 'G-6L1NQTGWLR',
  );
}
