// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR7LtND8LkRVJVk32M4SWIpKm171FVgOg',
    appId: '1:595053243328:web:e3437208e6f3f5fb3b7625',
    messagingSenderId: '595053243328',
    projectId: 'restaurantreviews-8a8c5',
    authDomain: 'restaurantreviews-8a8c5.firebaseapp.com',
    storageBucket: 'restaurantreviews-8a8c5.firebasestorage.app',
    measurementId: 'G-MLKP9Y10GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1EaUqX67coGXxBgrU80rUisWk4dkrq4',
    appId: '1:595053243328:android:d83ecddaf4e5c89b3b7625',
    messagingSenderId: '595053243328',
    projectId: 'restaurantreviews-8a8c5',
    storageBucket: 'restaurantreviews-8a8c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9YAhGiae4qxe5rjL-rE0ZqKaLvPho7Kc',
    appId: '1:595053243328:ios:c1fe2117749997f93b7625',
    messagingSenderId: '595053243328',
    projectId: 'restaurantreviews-8a8c5',
    storageBucket: 'restaurantreviews-8a8c5.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReviews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9YAhGiae4qxe5rjL-rE0ZqKaLvPho7Kc',
    appId: '1:595053243328:ios:c1fe2117749997f93b7625',
    messagingSenderId: '595053243328',
    projectId: 'restaurantreviews-8a8c5',
    storageBucket: 'restaurantreviews-8a8c5.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReviews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR7LtND8LkRVJVk32M4SWIpKm171FVgOg',
    appId: '1:595053243328:web:0372c158079c29203b7625',
    messagingSenderId: '595053243328',
    projectId: 'restaurantreviews-8a8c5',
    authDomain: 'restaurantreviews-8a8c5.firebaseapp.com',
    storageBucket: 'restaurantreviews-8a8c5.firebasestorage.app',
    measurementId: 'G-TQ4ZM17HVS',
  );
}
