// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw11i4CQtUdPiBt8TBsjS5QAIoBqoKW9w',
    appId: '1:246825297028:web:c4a3552442b5243d9e4ed1',
    messagingSenderId: '246825297028',
    projectId: 'onlineshopapp-8761a',
    authDomain: 'onlineshopapp-8761a.firebaseapp.com',
    storageBucket: 'onlineshopapp-8761a.firebasestorage.app',
    measurementId: 'G-V3BHQ4G3QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM14v8Z_q0fuW5W5Mgacug-oNPa3cNRHE',
    appId: '1:246825297028:android:afe90769ec0497a39e4ed1',
    messagingSenderId: '246825297028',
    projectId: 'onlineshopapp-8761a',
    storageBucket: 'onlineshopapp-8761a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrcSgP4AFZBCHsvNkgma4CcSMoaJTlBLU',
    appId: '1:246825297028:ios:da50d69949fb692b9e4ed1',
    messagingSenderId: '246825297028',
    projectId: 'onlineshopapp-8761a',
    storageBucket: 'onlineshopapp-8761a.firebasestorage.app',
    iosBundleId: 'com.example.onlineShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrcSgP4AFZBCHsvNkgma4CcSMoaJTlBLU',
    appId: '1:246825297028:ios:da50d69949fb692b9e4ed1',
    messagingSenderId: '246825297028',
    projectId: 'onlineshopapp-8761a',
    storageBucket: 'onlineshopapp-8761a.firebasestorage.app',
    iosBundleId: 'com.example.onlineShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw11i4CQtUdPiBt8TBsjS5QAIoBqoKW9w',
    appId: '1:246825297028:web:67883131e4bcff899e4ed1',
    messagingSenderId: '246825297028',
    projectId: 'onlineshopapp-8761a',
    authDomain: 'onlineshopapp-8761a.firebaseapp.com',
    storageBucket: 'onlineshopapp-8761a.firebasestorage.app',
    measurementId: 'G-0X85NVH2LQ',
  );
}
