// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCILak9tuYMapysKDKbGO5SR-NaWSAxEyQ',
    appId: '1:597268819707:web:fbee783aaa7db950204a5e',
    messagingSenderId: '597268819707',
    projectId: 'restaurant-reviews-b09c0',
    authDomain: 'restaurant-reviews-b09c0.firebaseapp.com',
    storageBucket: 'restaurant-reviews-b09c0.firebasestorage.app',
    measurementId: 'G-EY9KHFE93Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHSttGvYc1eqjs5KBwTHymD-H5CAZH_U',
    appId: '1:597268819707:android:c34a127df3dfff59204a5e',
    messagingSenderId: '597268819707',
    projectId: 'restaurant-reviews-b09c0',
    storageBucket: 'restaurant-reviews-b09c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJKClKTLkslmFhkdP1qyrb0_laVjnkq4',
    appId: '1:597268819707:ios:659ec8f1c6373e30204a5e',
    messagingSenderId: '597268819707',
    projectId: 'restaurant-reviews-b09c0',
    storageBucket: 'restaurant-reviews-b09c0.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReviews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJKClKTLkslmFhkdP1qyrb0_laVjnkq4',
    appId: '1:597268819707:ios:659ec8f1c6373e30204a5e',
    messagingSenderId: '597268819707',
    projectId: 'restaurant-reviews-b09c0',
    storageBucket: 'restaurant-reviews-b09c0.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReviews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCILak9tuYMapysKDKbGO5SR-NaWSAxEyQ',
    appId: '1:597268819707:web:2f834bd01489fc67204a5e',
    messagingSenderId: '597268819707',
    projectId: 'restaurant-reviews-b09c0',
    authDomain: 'restaurant-reviews-b09c0.firebaseapp.com',
    storageBucket: 'restaurant-reviews-b09c0.firebasestorage.app',
    measurementId: 'G-ZS2J3GNRZP',
  );
}
